In [4]:
import pandas as pd

In [5]:
car = pd.read_csv(r"D:\Ved\tech\datasets\2. Cars Data1.csv")

In [6]:
car.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0

In [7]:
car.shape

(432, 15)

In [8]:
car.isnull()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
428,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
429,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
430,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
431,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
car.isnull().sum()

Make           4
Model          4
Type           4
Origin         4
DriveTrain     4
MSRP           4
Invoice        4
EngineSize     4
Cylinders      6
Horsepower     4
MPG_City       4
MPG_Highway    4
Weight         4
Wheelbase      4
Length         4
dtype: int64

In [10]:
car[car["Horsepower"].isnull()].index

Int64Index([30, 39, 161, 173], dtype='int64')

In [11]:
car[car["Cylinders"].isnull()].index

Int64Index([30, 39, 161, 173, 251, 252], dtype='int64')

In [12]:
car.loc[[30,39,161,173]]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
car.dropna(how = "all",inplace = True)

In [14]:
car.shape

(428, 15)

In [15]:
car.isnull().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      2
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

In [16]:
car["Cylinders"].fillna(car["Cylinders"].mean(), inplace = True)

In [17]:
car

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197.0,21.0,28.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242.0,20.0,26.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268.0,19.0,26.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170.0,22.0,29.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208.0,20.0,27.0,3823.0,109.0,186.0

In [18]:
car["Make"].value_counts()

Toyota           28
Chevrolet        27
Mercedes-Benz    26
Ford             23
BMW              20
Audi             19
Honda            17
Nissan           17
Volkswagen       15
Chrysler         15
Dodge            13
Mitsubishi       13
Volvo            12
Jaguar           12
Hyundai          12
Subaru           11
Pontiac          11
Mazda            11
Lexus            11
Kia              11
Buick             9
Mercury           9
Lincoln           9
Saturn            8
Cadillac          8
Suzuki            8
Infiniti          8
GMC               8
Acura             7
Porsche           7
Saab              7
Land Rover        3
Oldsmobile        3
Jeep              3
Scion             2
Isuzu             2
MINI              2
Hummer            1
Name: Make, dtype: int64

In [19]:
car[car["Origin"].isin(["Asia","Euprope"])]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,Toyota,MR2 Spyder convertible 2dr,Sports,Asia,Rear,"$25,130","$22,787",1.8,4.0,138.0,26.0,32.0,2195.0,97.0,153.0
401,Toyota,Tacoma,Truck,Asia,Rear,"$12,800","$11,879",2.4,4.0,142.0,22.0,27.0,2750.0,103.0,191.0
402,Toyota,Tundra Regular Cab V6,Truck,Asia,Rear,"$16,495","$14,978",3.4,6.0,190.0,16.0,18.0,3925.0,128.0,218.0
403,Toyota,Tundra Access Cab V6 SR5,Truck,Asia,All,"$25,935","$23,520",3.4,6.0,190.0,14.0,17.0,4435.0,128.0,218.0
404,Toyota,Matrix XR,Wagon,Asia,Front,"$16,695","$15,156",1.8,4.0,130.0,29.0,36.0,2679.0,102.0,171.0

In [20]:
car["MPG_City"] = car["MPG_City"].apply(lambda x:x+3)

In [21]:
car

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,20.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,27.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,25.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,23.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,21.0,24.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197.0,24.0,28.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242.0,23.0,26.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268.0,22.0,26.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170.0,25.0,29.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208.0,23.0,27.0,3823.0,109.0,186.0

In [22]:
car = car[~(car["Weight"]>4500)]

In [23]:
car

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,20.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,27.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,25.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,23.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,21.0,24.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197.0,24.0,28.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242.0,23.0,26.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268.0,22.0,26.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170.0,25.0,29.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208.0,23.0,27.0,3823.0,109.0,186.0

In [24]:
car.to_csv()

',Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length\r\n0,Acura,MDX,SUV,Asia,All,"$36,945 ","$33,337 ",3.5,6.0,265.0,20.0,23.0,4451.0,106.0,189.0\r\n1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820 ","$21,761 ",2.0,4.0,200.0,27.0,31.0,2778.0,101.0,172.0\r\n2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990 ","$24,647 ",2.4,4.0,200.0,25.0,29.0,3230.0,105.0,183.0\r\n3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195 ","$30,299 ",3.2,6.0,270.0,23.0,28.0,3575.0,108.0,186.0\r\n4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755 ","$39,014 ",3.5,6.0,225.0,21.0,24.0,3880.0,115.0,197.0\r\n5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100 ","$41,100 ",3.5,6.0,225.0,21.0,24.0,3893.0,115.0,197.0\r\n6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765 ","$79,978 ",3.2,6.0,290.0,20.0,24.0,3153.0,100.0,174.0\r\n7,Audi,A4 1.8T 4dr,Sedan,Europe,Front,"$25,940 ","$23,508 ",1.8,4.0,170.0,25.0,31.0,3252.0,104.0,179.0\r\n8,Audi,A41.8T convertible 2dr,Sedan,Europe,Front,"$35,940 ","$32,506 ",1.8,4.0,170.0,26.0,30.0,3638.0,105.0,180.0\r\n9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840 ","$28,846 ",3.0,6.0,220.0,23.0,28.0,3462.0,104.0,179.0\r\n10,Audi,A4 3.0 Quattro 4dr manual,Sedan,Europe,All,"$33,430 ","$30,366 ",3.0,6.0,220.0,20.0,26.0,3583.0,104.0,179.0\r\n11,Audi,A4 3.0 Quattro 4dr auto,Sedan,Europe,All,"$34,480 ","$31,388 ",3.0,6.0,220.0,21.0,25.0,3627.0,104.0,179.0\r\n12,Audi,A6 3.0 4dr,Sedan,Europe,Front,"$36,640 ","$33,129 ",3.0,6.0,220.0,23.0,27.0,3561.0,109.0,192.0\r\n13,Audi,A6 3.0 Quattro 4dr,Sedan,Europe,All,"$39,640 ","$35,992 ",3.0,6.0,220.0,21.0,25.0,3880.0,109.0,192.0\r\n14,Audi,A4 3.0 convertible 2dr,Sedan,Europe,Front,"$42,490 ","$38,325 ",3.0,6.0,220.0,23.0,27.0,3814.0,105.0,180.0\r\n15,Audi,A4 3.0 Quattro convertible 2dr,Sedan,Europe,All,"$44,240 ","$40,075 ",3.0,6.0,220.0,21.0,25.0,4013.0,105.0,180.0\r\n16,Audi,A6 2.7 Turbo Quattro 4dr,Sedan,Europe,All,"$42,840 ","$38,840 ",2.7,6.0,250.0,21.0,25.0,3836.0,109.0,192.0\r\n17,Audi,A6 4.2 Quattro 4dr,Sedan,Europe,All,"$49,690 ","$44,936 ",4.2,8.0,300.0,20.0,24.0,4024.0,109.0,193.0\r\n18,Audi,A8 L Quattro 4dr,Sedan,Europe,All,"$69,190 ","$64,740 ",4.2,8.0,330.0,20.0,24.0,4399.0,121.0,204.0\r\n19,Audi,S4 Quattro 4dr,Sedan,Europe,All,"$48,040 ","$43,556 ",4.2,8.0,340.0,17.0,20.0,3825.0,104.0,179.0\r\n20,Audi,RS 6 4dr,Sports,Europe,Front,"$84,600 ","$76,417 ",4.2,8.0,450.0,18.0,22.0,4024.0,109.0,191.0\r\n21,Audi,TT 1.8 convertible 2dr (coupe),Sports,Europe,Front,"$35,940 ","$32,512 ",1.8,4.0,180.0,23.0,28.0,3131.0,95.0,159.0\r\n22,Audi,TT 1.8 Quattro 2dr (convertible),Sports,Europe,All,"$37,390 ","$33,891 ",1.8,4.0,225.0,23.0,28.0,2921.0,96.0,159.0\r\n23,Audi,TT 3.2 coupe 2dr (convertible),Sports,Europe,All,"$40,590 ","$36,739 ",3.2,6.0,250.0,24.0,29.0,3351.0,96.0,159.0\r\n24,Audi,A6 3.0 Avant Quattro,Wagon,Europe,All,"$40,840 ","$37,060 ",3.0,6.0,220.0,21.0,25.0,4035.0,109.0,192.0\r\n25,Audi,S4 Avant Quattro,Wagon,Europe,All,"$49,090 ","$44,446 ",4.2,8.0,340.0,18.0,21.0,3936.0,104.0,179.0\r\n26,BMW,X3 3.0i,SUV,Europe,All,"$37,000 ","$33,873 ",3.0,6.0,225.0,19.0,23.0,4023.0,110.0,180.0\r\n28,BMW,325i 4dr,Sedan,Europe,Rear,"$28,495 ","$26,155 ",2.5,6.0,184.0,23.0,29.0,3219.0,107.0,176.0\r\n29,BMW,325Ci 2dr,Sedan,Europe,Rear,"$30,795 ","$28,245 ",2.5,6.0,184.0,23.0,29.0,3197.0,107.0,177.0\r\n31,BMW,325Ci convertible 2dr,Sedan,Europe,Rear,"$37,995 ","$34,800 ",2.5,6.0,184.0,22.0,27.0,3560.0,107.0,177.0\r\n32,BMW,325xi 4dr,Sedan,Europe,All,"$30,245 ","$27,745 ",2.5,6.0,184.0,22.0,27.0,3461.0,107.0,176.0\r\n33,BMW,330i 4dr,Sedan,Europe,Rear,"$35,495 ","$32,525 ",3.0,6.0,225.0,23.0,30.0,3285.0,107.0,176.0\r\n34,BMW,330Ci 2dr,Sedan,Europe,Rear,"$36,995 ","$33,890 ",3.0,6.0,225.0,23.0,30.0,3285.0,107.0,176.0\r\n35,BMW,330xi 4dr,Sedan,Europe,All,"$37,245 ","$34,115 ",3.0,6.0,225.0,23.0,29.0,3483.0,107.0,176.0\r\n36,BMW,525i 4dr,Sedan,Europe,Rear,"$39,995 ","$36,620 ",2.5,6.0,184.0,22.0,28.0,3428.0,114.0,191.0\r\n37,BMW,330Ci convertible 2dr,Sedan,Europe,Rear,"$44,295 ","$40,530 ",3.0,6.0,225.0,22.0,28.0,3616.0,107.0,177.0\r\n38,BMW,530i 4dr,Sedan,Europe,Rear,"$44,995 ","$41,170 ",3.0,6.0,225.0,23.0,30.0,3472.0,114.0,191.0\r\n40,BMW,545iA 4dr,Sedan,Europe,Rear,"$54,995 ","$50,270 ",4.4,8.0,325.0,21.0,26.0,3814.0,114.0,191.0\r\n41,BMW,745i 4dr,Sedan,Europe,Rear,"$69,195 ","$63,190 ",4.4,8.0,325.0,21.0,26.0,4376.0,118.0,198.0\r\n42,BMW,745Li 4dr,Sedan,Europe,Rear,"$73,195 ","$66,830 ",4.4,8.0,325.0,21.0,26.0,4464.0,123.0,204.0\r\n43,BMW,M3 coupe 2dr,Sports,Europe,Rear,"$48,195 ","$44,170 ",3.2,6.0,333.0,19.0,24.0,3415.0,108.0,177.0\r\n44,BMW,M3 convertible 2dr,Sports,Europe,Rear,"$56,595 ","$51,815 ",3.2,6.0,333.0,19.0,23.0,3781.0,108.0,177.0\r\n45,BMW,Z4 convertible 2.5i 2dr,Sports,Europe,Rear,"$33,895 ","$31,065 ",2.5,6.0,184.0,23.0,28.0,2932.0,98.0,161.0\r\n46,BMW,Z4 convertible 3.0i 2dr,Sports,Europe,Rear,"$41,045 ","$37,575 ",3.0,6.0,225.0,24.0,29.0,2998.0,98.0,161.0\r\n47,BMW,325xi Sport,Wagon,Europe,All,"$32,845 ","$30,110 ",2.5,6.0,184.0,22.0,26.0,3594.0,107.0,176.0\r\n49,Buick,Rendezvous CX,SUV,USA,Front,"$26,545 ","$24,085 ",3.4,6.0,185.0,22.0,26.0,4024.0,112.0,187.0\r\n50,Buick,Century Custom 4dr,Sedan,USA,Front,"$22,180 ","$20,351 ",3.1,6.0,175.0,23.0,30.0,3353.0,109.0,195.0\r\n51,Buick,LeSabre Custom 4dr,Sedan,USA,Front,"$26,470 ","$24,282 ",3.8,6.0,205.0,23.0,29.0,3567.0,112.0,200.0\r\n52,Buick,Regal LS 4dr,Sedan,USA,Front,"$24,895 ","$22,835 ",3.8,6.0,200.0,23.0,30.0,3461.0,109.0,196.0\r\n53,Buick,Regal GS 4dr,Sedan,USA,Front,"$28,345 ","$26,047 ",3.8,6.0,240.0,21.0,28.0,3536.0,109.0,196.0\r\n54,Buick,LeSabre Limited 4dr,Sedan,USA,Front,"$32,245 ","$29,566 ",3.8,6.0,205.0,23.0,29.0,3591.0,112.0,200.0\r\n55,Buick,Park Avenue 4dr,Sedan,USA,Front,"$35,545 ","$32,244 ",3.8,6.0,205.0,23.0,29.0,3778.0,114.0,207.0\r\n56,Buick,Park Avenue Ultra 4dr,Sedan,USA,Front,"$40,720 ","$36,927 ",3.8,6.0,240.0,21.0,28.0,3909.0,114.0,207.0\r\n58,Cadillac,SRX V8,SUV,USA,Front,"$46,995 ","$43,523 ",4.6,8.0,320.0,19.0,21.0,4302.0,116.0,195.0\r\n59,Cadillac,CTS VVT 4dr,Sedan,USA,Rear,"$30,835 ","$28,575 ",3.6,6.0,255.0,21.0,25.0,3694.0,113.0,190.0\r\n60,Cadillac,Deville 4dr,Sedan,USA,Front,"$45,445 ","$41,650 ",4.6,8.0,275.0,21.0,26.0,3984.0,115.0,207.0\r\n61,Cadillac,Deville DTS 4dr,Sedan,USA,Front,"$50,595 ","$46,362 ",4.6,8.0,300.0,21.0,26.0,4044.0,115.0,207.0\r\n62,Cadillac,Seville SLS 4dr,Sedan,USA,Front,"$47,955 ","$43,841 ",4.6,8.0,275.0,21.0,26.0,3992.0,112.0,201.0\r\n63,Cadillac,XLR convertible 2dr,Sports,USA,Rear,"$76,200 ","$70,546 ",4.6,8.0,320.0,20.0,25.0,3647.0,106.0,178.0\r\n67,Chevrolet,TrailBlazer LT,SUV,USA,Front,"$30,295 ","$27,479 ",4.2,6.0,275.0,19.0,21.0,4425.0,113.0,192.0\r\n68,Chevrolet,Tracker,SUV,USA,Front,"$20,255 ","$19,108 ",2.5,6.0,165.0,22.0,22.0,2866.0,98.0,163.0\r\n69,Chevrolet,Aveo 4dr,Sedan,USA,Front,"$11,690 ","$10,965 ",1.6,4.0,103.0,31.0,34.0,2370.0,98.0,167.0\r\n70,Chevrolet,Aveo LS 4dr hatch,Sedan,USA,Front,"$12,585 ","$11,802 ",1.6,4.0,103.0,31.0,34.0,2348.0,98.0,153.0\r\n71,Chevrolet,Cavalier 2dr,Sedan,USA,Front,"$14,610 ","$13,697 ",2.2,4.0,140.0,29.0,37.0,2617.0,104.0,183.0\r\n72,Chevrolet,Cavalier 4dr,Sedan,USA,Front,"$14,810 ","$13,884 ",2.2,4.0,140.0,29.0,37.0,2676.0,104.0,183.0\r\n73,Chevrolet,Cavalier LS 2dr,Sedan,USA,Front,"$16,385 ","$15,357 ",2.2,4.0,140.0,29.0,37.0,2617.0,104.0,183.0\r\n74,Chevrolet,Impala 4dr,Sedan,USA,Front,"$21,900 ","$20,095 ",3.4,6.0,180.0,24.0,32.0,3465.0,111.0,200.0\r\n75,Chevrolet,Malibu 4dr,Sedan,USA,Front,"$18,995 ","$17,434 ",2.2,4.0,145.0,27.0,34.0,3174.0,106.0,188.0\r\n76,Chevrolet,Malibu LS 4dr,Sedan,USA,Front,"$20,370 ","$18,639 ",3.5,6.0,200.0,25.0,30.0,3297.0,106.0,188.0\r\n77,Chevrolet,Monte Carlo LS 2dr,Sedan,USA,Front,"$21,825 ","$20,026 ",3.4,6.0,180.0,24.0,32.0,3340.0,111.0,198.0\r\n78,Chevrolet,Impala LS 4dr,Sedan,USA,Front,"$25,000 ","$22,931 ",3.8,6.0,200.0,23.0,30.0,3476.0,111.0,200.0\r\n79,Chevrolet,Impala SS 4dr,Sedan,USA,Front,"$27,995 ","$25,672 ",3.8,6.0,240.0,21.0,28.0,3606.0,111.0,200.0\r\n80,Chevrolet,Malibu LT 4dr,Sedan,USA,Front,"$23,495 ","$21,551 ",3.5,6.0,200.0,26.0,32.0,3315.0,106.0,188.0\r\n81,Chevrolet,Monte Carlo SS 2dr,Sedan,USA,Front,"$24,225 ","$22,222 ",3.8,6.0,200.0,21.0,28.0,3434.0,111.0,198.0\r\n83,Chevrolet,Venture LS,Sedan,USA,Front,"$27,020 ","$24,518 ",3.4,6.0,185.0,22.0,26.0,3699.0,112.0,187.0\r\n84,Chevrolet,Corvette 2dr,Sports,USA,Rear,"$44,535 ","$39,068 ",5.7,8.0,350.0,21.0,25.0,3246.0,105.0,180.0\r\n85,Chevrolet,Corvette convertible 2dr,Sports,USA,Rear,"$51,535 ","$45,193 ",5.7,8.0,350.0,21.0,25.0,3248.0,105.0,180.0\r\n87,Chevrolet,Colorado Z85,Truck,USA,All,"$18,760 ","$17,070 ",2.8,4.0,175.0,21.0,23.0,3623.0,111.0,192.0\r\n88,Chevrolet,Silverado 1500 Regular Cab,Truck,USA,Rear,"$20,310 ","$18,480 ",4.3,6.0,200.0,18.0,21.0,4142.0,119.0,206.0\r\n91,Chevrolet,Malibu Maxx LS,Wagon,USA,Front,"$22,225 ","$20,394 ",3.5,6.0,200.0,25.0,30.0,3458.0,112.0,188.0\r\n92,Chrysler,PT Cruiser 4dr,Sedan,USA,Front,"$17,985 ","$16,919 ",2.4,4.0,150.0,25.0,29.0,3101.0,103.0,169.0\r\n93,Chrysler,PT Cruiser Limited 4dr,Sedan,USA,Front,"$22,000 ","$20,573 ",2.4,4.0,150.0,25.0,29.0,3105.0,103.0,169.0\r\n94,Chrysler,Sebring 4dr,Sedan,USA,Front,"$19,090 ","$17,805 ",2.4,4.0,150.0,25.0,30.0,3173.0,108.0,191.0\r\n95,Chrysler,Sebring Touring 4dr,Sedan,USA,Front,"$21,840 ","$20,284 ",2.7,6.0,200.0,24.0,28.0,3222.0,108.0,191.0\r\n96,Chrysler,300M 4dr,Sedan,USA,Front,"$29,865 ","$27,797 ",3.5,6.0,250.0,21.0,27.0,3581.0,113.0,198.0\r\n97,Chrysler,Concorde LX 4dr,Sedan,USA,Front,"$24,130 ","$22,452 ",2.7,6.0,200.0,24.0,29.0,3479.0,113.0,208.0\r\n98,Chrysler,Concorde LXi 4dr,Sedan,USA,Front,"$26,860 ","$24,909 ",3.5,6.0,232.0,22.0,27.0,3548.0,113.0,208.0\r\n99,Chrysler,PT Cruiser GT 4dr,Sedan,USA,Front,"$25,955 ","$24,172 ",2.4,4.0,220.0,24.0,27.0,3217.0,103.0,169.0\r\n100,Chrysler,Sebring convertible 2dr,Sedan,USA,Front,"$25,215 ","$23,451 ",2.4,4.0,150.0,25.0,30.0,3357.0,106.0,194.0\r\n101,Chrysler,300M Special Edition 4dr,Sedan,USA,Front,"$33,295 ","$30,884 ",3.5,6.0,255.0,21.0,27.0,3650.0,113.0,198.0\r\n102,Chrysler,Sebring Limited convertible 2dr,Sedan,USA,Front,"$30,950 ","$28,613 ",2.7,6.0,200.0,24.0,28.0,3448.0,106.0,194.0\r\n103,Chrysler,Town and Country LX,Sedan,USA,Front,"$27,490 ","$25,371 ",3.3,6.0,180.0,22.0,26.0,4068.0,119.0,201.0\r\n104,Chrysler,Town and Country Limited,Sedan,USA,Front,"$38,380 ","$35,063 ",3.8,6.0,215.0,21.0,25.0,4331.0,119.0,201.0\r\n105,Chrysler,Crossfire 2dr,Sports,USA,Rear,"$34,495 ","$32,033 ",3.2,6.0,215.0,20.0,25.0,3060.0,95.0,160.0\r\n108,Dodge,Neon SE 4dr,Sedan,USA,Front,"$13,670 ","$12,849 ",2.0,4.0,132.0,32.0,36.0,2581.0,105.0,174.0\r\n109,Dodge,Neon SXT 4dr,Sedan,USA,Front,"$15,040 ","$14,086 ",2.0,4.0,132.0,32.0,36.0,2626.0,105.0,174.0\r\n110,Dodge,Intrepid SE 4dr,Sedan,USA,Front,"$22,035 ","$20,502 ",2.7,6.0,200.0,24.0,29.0,3469.0,113.0,204.0\r\n111,Dodge,Stratus SXT 4dr,Sedan,USA,Front,"$18,820 ","$17,512 ",2.4,4.0,150.0,24.0,28.0,3182.0,108.0,191.0\r\n112,Dodge,Stratus SE 4dr,Sedan,USA,Front,"$20,220 ","$18,821 ",2.4,4.0,150.0,24.0,28.0,3175.0,108.0,191.0\r\n113,Dodge,Intrepid ES 4dr,Sedan,USA,Front,"$24,885 ","$23,058 ",3.5,6.0,232.0,21.0,27.0,3487.0,113.0,204.0\r\n114,Dodge,Caravan SE,Sedan,USA,Front,"$21,795 ","$20,508 ",2.4,4.0,150.0,23.0,26.0,3862.0,113.0,189.0\r\n115,Dodge,Grand Caravan SXT,Sedan,USA,All,"$32,660 ","$29,812 ",3.8,6.0,215.0,21.0,25.0,4440.0,119.0,201.0\r\n116,Dodge,Viper SRT-10 convertible 2dr,Sports,USA,Rear,"$81,795 ","$74,451 ",8.3,10.0,500.0,15.0,20.0,3410.0,99.0,176.0\r\n117,Dodge,Dakota Regular Cab,Truck,USA,Rear,"$17,630 ","$16,264 ",3.7,6.0,210.0,19.0,22.0,3714.0,112.0,193.0\r\n118,Dodge,Dakota Club Cab,Truck,USA,Rear,"$20,300 ","$18,670 ",3.7,6.0,210.0,19.0,22.0,3829.0,131.0,219.0\r\n122,Ford,Explorer XLT V6,SUV,USA,All,"$29,670 ","$26,983 ",4.0,6.0,210.0,18.0,20.0,4463.0,114.0,190.0\r\n123,Ford,Escape XLS,SUV,USA,All,"$22,515 ","$20,907 ",3.0,6.0,201.0,21.0,23.0,3346.0,103.0,173.0\r\n124,Ford,Focus ZX3 2dr hatch,Sedan,USA,Front,"$13,270 ","$12,482 ",2.0,4.0,130.0,29.0,33.0,2612.0,103.0,168.0\r\n125,Ford,Focus LX 4dr,Sedan,USA,Front,"$13,730 ","$12,906 ",2.0,4.0,110.0,30.0,36.0,2606.0,103.0,168.0\r\n126,Ford,Focus SE 4dr,Sedan,USA,Front,"$15,460 ","$14,496 ",2.0,4.0,130.0,29.0,33.0,2606.0,103.0,168.0\r\n127,Ford,Focus ZX5 5dr,Sedan,USA,Front,"$15,580 ","$14,607 ",2.0,4.0,130.0,29.0,33.0,2691.0,103.0,168.0\r\n128,Ford,Focus SVT 2dr,Sedan,USA,Front,"$19,135 ","$17,878 ",2.0,4.0,170.0,24.0,28.0,2750.0,103.0,168.0\r\n129,Ford,Taurus LX 4dr,Sedan,USA,Front,"$20,320 ","$18,881 ",3.0,6.0,155.0,23.0,27.0,3306.0,109.0,198.0\r\n130,Ford,Taurus SES Duratec 4dr,Sedan,USA,Front,"$22,735 ","$20,857 ",3.0,6.0,201.0,22.0,26.0,3313.0,109.0,198.0\r\n131,Ford,Crown Victoria 4dr,Sedan,USA,Rear,"$24,345 ","$22,856 ",4.6,8.0,224.0,20.0,25.0,4057.0,115.0,212.0\r\n132,Ford,Crown Victoria LX 4dr,Sedan,USA,Rear,"$27,370 ","$25,105 ",4.6,8.0,224.0,20.0,25.0,4057.0,115.0,212.0\r\n133,Ford,Crown Victoria LX Sport 4dr,Sedan,USA,Rear,"$30,315 ","$27,756 ",4.6,8.0,239.0,20.0,25.0,4057.0,115.0,212.0\r\n134,Ford,Freestar SE,Sedan,USA,Front,"$26,930 ","$24,498 ",3.9,6.0,193.0,20.0,23.0,4275.0,121.0,201.0\r\n135,Ford,Mustang 2dr (convertible),Sports,USA,Rear,"$18,345 ","$16,943 ",3.8,6.0,193.0,23.0,29.0,3290.0,101.0,183.0\r\n136,Ford,Mustang GT Premium convertible 2dr,Sports,USA,Rear,"$29,380 ","$26,875 ",4.6,8.0,260.0,20.0,25.0,3347.0,101.0,183.0\r\n137,Ford,Thunderbird Deluxe convert w/hardtop 2d,Sports,USA,Front,"$37,530 ","$34,483 ",3.9,8.0,280.0,20.0,24.0,3780.0,107.0,186.0\r\n140,Ford,Ranger 2.3 XL Regular Cab,Truck,USA,Rear,"$14,385 ","$13,717 ",2.3,4.0,143.0,27.0,29.0,3028.0,111.0,188.0\r\n141,Ford,Focus ZTW,Wagon,USA,Front,"$17,475 ","$16,375 ",2.0,4.0,130.0,29.0,33.0,2702.0,103.0,178.0\r\n142,Ford,Taurus SE,Wagon,USA,Front,"$22,290 ","$20,457 ",3.0,6.0,155.0,22.0,26.0,3497.0,109.0,198.0\r\n146,GMC,Safari SLE,Sedan,USA,Rear,"$25,640 ","$23,215 ",4.3,6.0,190.0,19.0,20.0,4309.0,111.0,190.0\r\n147,GMC,Canyon Z85 SL Regular Cab,Truck,USA,Rear,"$16,530 ","$14,877 ",2.8,4.0,175.0,21.0,25.0,3351.0,111.0,192.0\r\n150,GMC,Sonoma Crew Cab,Truck,USA,All,"$25,395 ","$23,043 ",4.3,6.0,190.0,18.0,19.0,4083.0,123.0,208.0\r\n151,Honda,Civic Hybrid 4dr manual (gas/electric),Hybrid,Asia,Front,"$20,140 ","$18,451 ",1.4,4.0,93.0,49.0,51.0,2732.0,103.0,175.0\r\n152,Honda,Insight 2dr (gas/electric),Hybrid,Asia,Front,"$19,110 ","$17,911 ",2.0,3.0,73.0,63.0,66.0,1850.0,95.0,155.0\r\n153,Honda,Pilot LX,SUV,Asia,All,"$27,560 ","$24,843 ",3.5,6.0,240.0,20.0,22.0,4387.0,106.0,188.0\r\n154,Honda,CR-V LX,SUV,Asia,All,"$19,860 ","$18,419 ",2.4,4.0,160.0,24.0,25.0,3258.0,103.0,179.0\r\n155,Honda,Element LX,SUV,Asia,All,"$18,690 ","$17,334 ",2.4,4.0,160.0,24.0,24.0,3468.0,101.0,167.0\r\n156,Honda,Civic DX 2dr,Sedan,Asia,Front,"$13,270 ","$12,175 ",1.7,4.0,115.0,35.0,38.0,2432.0,103.0,175.0\r\n157,Honda,Civic HX 2dr,Sedan,Asia,Front,"$14,170 ","$12,996 ",1.7,4.0,117.0,39.0,44.0,2500.0,103.0,175.0\r\n158,Honda,Civic LX 4dr,Sedan,Asia,Front,"$15,850 ","$14,531 ",1.7,4.0,115.0,35.0,38.0,2513.0,103.0,175.0\r\n159,Honda,Accord LX 2dr,Sedan,Asia,Front,"$19,860 ","$17,924 ",2.4,4.0,160.0,29.0,34.0,2994.0,105.0,188.0\r\n160,Honda,Accord EX 2dr,Sedan,Asia,Front,"$22,260 ","$20,080 ",2.4,4.0,160.0,29.0,34.0,3047.0,105.0,188.0\r\n162,Honda,Civic EX 4dr,Sedan,Asia,Front,"$17,750 ","$16,265 ",1.7,4.0,127.0,35.0,37.0,2601.0,103.0,175.0\r\n163,Honda,Civic Si 2dr hatch,Sedan,Asia,Front,"$19,490 ","$17,849 ",2.0,4.0,160.0,29.0,30.0,2782.0,101.0,166.0\r\n164,Honda,Accord LX V6 4dr,Sedan,Asia,Front,"$23,760 ","$21,428 ",3.0,6.0,240.0,24.0,30.0,3349.0,108.0,190.0\r\n165,Honda,Accord EX V6 2dr,Sedan,Asia,Front,"$26,960 ","$24,304 ",3.0,6.0,240.0,24.0,30.0,3294.0,105.0,188.0\r\n166,Honda,Odyssey LX,Sedan,Asia,Front,"$24,950 ","$22,498 ",3.5,6.0,240.0,21.0,25.0,4310.0,118.0,201.0\r\n167,Honda,Odyssey EX,Sedan,Asia,Front,"$27,450 ","$24,744 ",3.5,6.0,240.0,21.0,25.0,4365.0,118.0,201.0\r\n168,Honda,S2000 convertible 2dr,Sports,Asia,Rear,"$33,260 ","$29,965 ",2.2,4.0,240.0,23.0,25.0,2835.0,95.0,162.0\r\n170,Hyundai,Santa Fe GLS,SUV,Asia,Front,"$21,589 ","$20,201 ",2.7,6.0,173.0,23.0,26.0,3549.0,103.0,177.0\r\n171,Hyundai,Accent 2dr hatch,Sedan,Asia,Front,"$10,539 ","$10,107 ",1.6,4.0,103.0,32.0,33.0,2255.0,96.0,167.0\r\n172,Hyundai,Accent GL 4dr,Sedan,Asia,Front,"$11,839 ","$11,116 ",1.6,4.0,103.0,32.0,33.0,2290.0,96.0,167.0\r\n174,Hyundai,Accent GT 2dr hatch,Sedan,Asia,Front,"$11,939 ","$11,209 ",1.6,4.0,103.0,32.0,33.0,2339.0,96.0,167.0\r\n175,Hyundai,Elantra GLS 4dr,Sedan,Asia,Front,"$13,839 ","$12,781 ",2.0,4.0,138.0,29.0,34.0,2635.0,103.0,178.0\r\n176,Hyundai,Elantra GT 4dr,Sedan,Asia,Front,"$15,389 ","$14,207 ",2.0,4.0,138.0,29.0,34.0,2635.0,103.0,178.0\r\n177,Hyundai,Elantra GT 4dr hatch,Sedan,Asia,Front,"$15,389 ","$14,207 ",2.0,4.0,138.0,29.0,34.0,2698.0,103.0,178.0\r\n178,Hyundai,Sonata GLS 4dr,Sedan,Asia,Front,"$19,339 ","$17,574 ",2.7,6.0,170.0,22.0,27.0,3217.0,106.0,187.0\r\n179,Hyundai,Sonata LX 4dr,Sedan,Asia,Front,"$20,339 ","$18,380 ",2.7,6.0,170.0,22.0,27.0,3217.0,106.0,187.0\r\n180,Hyundai,XG350 4dr,Sedan,Asia,Front,"$24,589 ","$22,055 ",3.5,6.0,194.0,20.0,26.0,3651.0,108.0,192.0\r\n181,Hyundai,XG350 L 4dr,Sedan,Asia,Front,"$26,189 ","$23,486 ",3.5,6.0,194.0,20.0,26.0,3651.0,108.0,192.0\r\n182,Hyundai,Tiburon GT V6 2dr,Sports,Asia,Front,"$18,739 ","$17,101 ",2.7,6.0,172.0,22.0,26.0,3023.0,100.0,173.0\r\n183,Infiniti,G35 4dr,Sedan,Asia,Rear,"$28,495 ","$26,157 ",3.5,6.0,260.0,21.0,26.0,3336.0,112.0,187.0\r\n184,Infiniti,G35 Sport Coupe 2dr,Sedan,Asia,Rear,"$29,795 ","$27,536 ",3.5,6.0,280.0,21.0,26.0,3416.0,112.0,182.0\r\n185,Infiniti,G35 4dr,Sedan,Asia,All,"$32,445 ","$29,783 ",3.5,6.0,260.0,21.0,26.0,3677.0,112.0,187.0\r\n186,Infiniti,I35 4dr,Sedan,Asia,Front,"$31,145 ","$28,320 ",3.5,6.0,255.0,22.0,26.0,3306.0,108.0,194.0\r\n187,Infiniti,M45 4dr,Sedan,Asia,Rear,"$42,845 ","$38,792 ",4.5,8.0,340.0,20.0,23.0,3851.0,110.0,197.0\r\n188,Infiniti,Q45 Luxury 4dr,Sedan,Asia,Rear,"$52,545 ","$47,575 ",4.5,8.0,340.0,20.0,23.0,3977.0,113.0,200.0\r\n189,Infiniti,FX35,Wagon,Asia,Rear,"$34,895 ","$31,756 ",3.5,6.0,280.0,19.0,22.0,4056.0,112.0,189.0\r\n190,Infiniti,FX45,Wagon,Asia,All,"$36,395 ","$33,121 ",4.5,8.0,315.0,18.0,19.0,4309.0,112.0,189.0\r\n192,Isuzu,Rodeo S,SUV,Asia,Front,"$20,449 ","$19,261 ",3.2,6.0,193.0,20.0,21.0,3836.0,106.0,178.0\r\n193,Jaguar,X-Type 2.5 4dr,Sedan,Europe,All,"$29,995 ","$27,355 ",2.5,6.0,192.0,21.0,26.0,3428.0,107.0,184.0\r\n194,Jaguar,X-Type 3.0 4dr,Sedan,Europe,All,"$33,995 ","$30,995 ",3.0,6.0,227.0,21.0,25.0,3516.0,107.0,184.0\r\n195,Jaguar,S-Type 3.0 4dr,Sedan,Europe,Rear,"$43,895 ","$40,004 ",3.0,6.0,235.0,21.0,26.0,3777.0,115.0,192.0\r\n196,Jaguar,S-Type 4.2 4dr,Sedan,Europe,Rear,"$49,995 ","$45,556 ",4.2,8.0,294.0,21.0,28.0,3874.0,115.0,192.0\r\n197,Jaguar,S-Type R 4dr,Sedan,Europe,Rear,"$63,120 ","$57,499 ",4.2,8.0,390.0,20.0,24.0,4046.0,115.0,192.0\r\n198,Jaguar,Vanden Plas 4dr,Sedan,Europe,Rear,"$68,995 ","$62,846 ",4.2,8.0,294.0,21.0,28.0,3803.0,119.0,200.0\r\n199,Jaguar,XJ8 4dr,Sedan,Europe,Rear,"$59,995 ","$54,656 ",4.2,8.0,294.0,21.0,28.0,3803.0,119.0,200.0\r\n200,Jaguar,XJR 4dr,Sedan,Europe,Rear,"$74,995 ","$68,306 ",4.2,8.0,390.0,20.0,24.0,3948.0,119.0,200.0\r\n201,Jaguar,XK8 coupe 2dr,Sports,Europe,Rear,"$69,995 ","$63,756 ",4.2,8.0,294.0,21.0,26.0,3779.0,102.0,187.0\r\n202,Jaguar,XK8 convertible 2dr,Sports,Europe,Rear,"$74,995 ","$68,306 ",4.2,8.0,294.0,21.0,26.0,3980.0,102.0,187.0\r\n203,Jaguar,XKR coupe 2dr,Sports,Europe,Rear,"$81,995 ","$74,676 ",4.2,8.0,390.0,19.0,23.0,3865.0,102.0,187.0\r\n204,Jaguar,XKR convertible 2dr,Sports,Europe,Rear,"$86,995 ","$79,226 ",4.2,8.0,390.0,19.0,23.0,4042.0,102.0,187.0\r\n205,Jeep,Grand Cherokee Laredo,SUV,USA,Front,"$27,905 ","$25,686 ",4.0,6.0,195.0,19.0,21.0,3790.0,106.0,181.0\r\n206,Jeep,Liberty Sport,SUV,USA,All,"$20,130 ","$18,973 ",2.4,4.0,150.0,23.0,24.0,3826.0,104.0,174.0\r\n207,Jeep,Wrangler Sahara convertible 2dr,SUV,USA,All,"$25,520 ","$23

In [25]:
car.to_csv("D:/Ved/tech/datasets/cars_cleaned.csv")